name: Telegram → VK

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

jobs:
  run:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install
        run: |
          pip install -r requirements.txt

      - name: Run
        env:
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TG_CHANNEL: ${{ secrets.TG_CHANNEL }}
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          VK_GROUP_ID: ${{ secrets.VK_GROUP_ID }}
        run: |
          python app.py

      - name: Save state
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update state
